language: java
jdk: oraclejdk8

matrix:
  include:
    - os: linux
      dist: trusty
    - os: windows

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

cache:
  directories:
    - $HOME/.m2

script: mvn clean verify
